In [1]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

In [2]:
# Read csv data into Pandas DataFrame
listings_df = pd.read_csv("Resources/listings.csv")
listings_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,138592,https://www.airbnb.com/rooms/138592,20231204023824,2023-12-04,city scrape,Home in San Francisco · ★4.91 · 4 bedrooms · 4...,NaN,The home is walking distance from lots of loca...,https://a0.muscache.com/pictures/039b1662-ff1a...,648553,...,4.91,5.00,4.55,Pending Application,f,1,1,0,0,0.23
1,474107,https://www.airbnb.com/rooms/474107,20231204023824,2023-12-04,city scrape,Home in San Francisco · ★4.91 · 2 bedrooms · 2...,NaN,Excelsior is south of the Mission district and...,https://a0.muscache.com/pictures/181cbeb0-18b7...,2318089,...,4.99,4.76,4.87,STR-0007772,f,1,0,1,0,1.92
2,487019,https://www.airbnb.com/rooms/487019,20231204023824,2023-12-04,city scrape,Rental unit in San Francisco · ★4.53 · 3 bedro...,NaN,A gourmet hidden gem with spectacular views of...,https://a0.muscache.com/pictures/5789289/7a78c...,2410550,...,4.72,4.36,4.47,STR-0001599,f,1,1,0,0,0.26
3,487499,https://www.airbnb.com/rooms/487499,20231204023824,2023-12-04,city scrape,Rental unit in San Francisco · ★4.78 · 1 bedro...,NaN,The Mission Dolores area is consider one of th...,https://a0.muscache.com/pictures/12842308/68a6...,1682183,...,4.92,4.85,4.60,NaN,f,1,1,0,0,1.41
4,1163946,https://www.airbnb.com/rooms/1163946,20231204023824,2023-12-04,previous scrape,Condo in San Francisco · 2 bedrooms · 2 beds ·...,NaN,the Mission is a simmering cauldron of culture...,https://a0.muscache.com/pictures/miso/Hosting-...,1918239,...,5.00,4.50,4.50,NaN,f,1,1,0,0,0.02

In [3]:
# Checking for null values on the column level
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8056 entries, 0 to 8055
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8056 non-null   int64
 1   listing_url                                   8056 non-null   object
 2   scrape_id                                     8056 non-null   int64
 3   last_scraped                                  8056 non-null   object
 4   source                                        8056 non-null   object
 5   name                                          8056 non-null   object
 6   description                                   0 non-null      float64
 7   neighborhood_overview                         5613 non-null   object
 8   picture_url                                   8056 non-null   object
 9   host_id                                       8056 non-null   int64
 10  host_url                                      8056 non-null   object
 11  host_name                                     8055 non-null   object
 12  host_since                                    8055 non-null   object
 13  host_location                                 6464 non-null   object
 14  host_about                                    4969 non-null   object
 15  host_response_time                            6747 non-null   object
 16  host_response_rate                            6747 non-null   object
 17  host_acceptance_rate                          7170 non-null   object
 18  host_is_superhost                             7992 non-null   object
 19  host_thumbnail_url                            8055 non-null   object
 20  host_picture_url                              8055 non-null   object
 21  host_neighbourhood                            7718 non-null   object
 22  host_listings_count                           8055 non-null   float64
 23  host_total_listings_count                     8055 non-null   float64
 24  host_verifications                            8055 non-null   object
 25  host_has_profile_pic                          8055 non-null   object
 26  host_identity_verified                        8055 non-null   object
 27  neighbourhood                                 5613 non-null   object
 28  neighbourhood_cleansed                        8056 non-null   object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      8056 non-null   float64
 31  longitude                                     8056 non-null   float64
 32  property_type                                 8056 non-null   object
 33  room_type                                     8056 non-null   object
 34  accommodates                                  8056 non-null   int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                8047 non-null   object
 37  bedrooms                                      5 non-null      float64
 38  beds                                          7959 non-null   float64
 39  amenities                                     8056 non-null   object
 40  price                                         8056 non-null   object
 41  minimum_nights                                8056 non-null   int64
 42  maximum_nights                                8056 non-null   int64
 43  minimum_minimum_nights                        8056 non-null   int64
 44  maximum_minimum_nights                        8056 non-null   int64
 45  minimum_maximum_nights                        8056 non-null   int64
 46  maximum_maximum_nights                        8056 non-null   int64
 47  minimum_nights_avg_ntm                        8056 non-null   float64
 48  maximum_nights_avg_ntm                        8056 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              8056 non-null   object
 51  availability_30                               8056 non-null   int64
 52  availability_60                               8056 non-null   int64
 53  availability_90                               8056 non-null   int64
 54  availability_365                              8056 non-null   int64
 55  calendar_last_scraped                         8056 non-null   object
 56  number_of_reviews                             8056 non-null   int64
 57  number_of_reviews_ltm                         8056 non-null   int64
 58  number_of_reviews_l30d                        8056 non-null   int64
 59  first_review                                  6172 non-null   object
 60  last_review                                   6172 non-null   object
 61  review_scores_rating                          6175 non-null   float64
 62  review_scores_accuracy                        6173 non-null   float64
 63  review_scores_cleanliness                     6173 non-null   float64
 64  review_scores_checkin                         6172 non-null   float64
 65  review_scores_communication                   6173 non-null   float64
 66  review_scores_location                        6172 non-null   float64
 67  review_scores_value                           6172 non-null   float64
 68  license                                       5091 non-null   object
 69  instant_bookable                              8056 non-null   object
 70  calculated_host_listings_count                8056 non-null   int64
 71  calculated_host_listings_count_entire_homes   8056 non-null   int64
 72  calculated_host_listings_count_private_rooms  8056 non-null   int64
 73  calculated_host_listings_count_shared_rooms   8056 non-null   int64
 74  reviews_per_month                             6172 non-null   float64
dtypes: float64(20), int64(21), object(34)
memory usage: 4.6+ MB

In [4]:
# Dropping all fully null columns
listings_df = listings_df.drop(['description', 'neighbourhood_group_cleansed', 'bathrooms', 'calendar_updated'], axis=1)
listings_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,138592,https://www.airbnb.com/rooms/138592,20231204023824,2023-12-04,city scrape,Home in San Francisco · ★4.91 · 4 bedrooms · 4...,The home is walking distance from lots of loca...,https://a0.muscache.com/pictures/039b1662-ff1a...,648553,https://www.airbnb.com/users/show/648553,...,4.91,5.00,4.55,Pending Application,f,1,1,0,0,0.23
1,474107,https://www.airbnb.com/rooms/474107,20231204023824,2023-12-04,city scrape,Home in San Francisco · ★4.91 · 2 bedrooms · 2...,Excelsior is south of the Mission district and...,https://a0.muscache.com/pictures/181cbeb0-18b7...,2318089,https://www.airbnb.com/users/show/2318089,...,4.99,4.76,4.87,STR-0007772,f,1,0,1,0,1.92
2,487019,https://www.airbnb.com/rooms/487019,20231204023824,2023-12-04,city scrape,Rental unit in San Francisco · ★4.53 · 3 bedro...,A gourmet hidden gem with spectacular views of...,https://a0.muscache.com/pictures/5789289/7a78c...,2410550,https://www.airbnb.com/users/show/2410550,...,4.72,4.36,4.47,STR-0001599,f,1,1,0,0,0.26
3,487499,https://www.airbnb.com/rooms/487499,20231204023824,2023-12-04,city scrape,Rental unit in San Francisco · ★4.78 · 1 bedro...,The Mission Dolores area is consider one of th...,https://a0.muscache.com/pictures/12842308/68a6...,1682183,https://www.airbnb.com/users/show/1682183,...,4.92,4.85,4.60,NaN,f,1,1,0,0,1.41
4,1163946,https://www.airbnb.com/rooms/1163946,20231204023824,2023-12-04,previous scrape,Condo in San Francisco · 2 bedrooms · 2 beds ·...,the Mission is a simmering cauldron of culture...,https://a0.muscache.com/pictures/miso/Hosting-...,1918239,https://www.airbnb.com/users/show/1918239,...,5.00,4.50,4.50,NaN,f,1,1,0,0,0.02

In [5]:
# Re-checking for null values on the column level
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8056 entries, 0 to 8055
Data columns (total 71 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8056 non-null   int64
 1   listing_url                                   8056 non-null   object
 2   scrape_id                                     8056 non-null   int64
 3   last_scraped                                  8056 non-null   object
 4   source                                        8056 non-null   object
 5   name                                          8056 non-null   object
 6   neighborhood_overview                         5613 non-null   object
 7   picture_url                                   8056 non-null   object
 8   host_id                                       8056 non-null   int64
 9   host_url                                      8056 non-null   object
 10  host_name                                     8055 non-null   object
 11  host_since                                    8055 non-null   object
 12  host_location                                 6464 non-null   object
 13  host_about                                    4969 non-null   object
 14  host_response_time                            6747 non-null   object
 15  host_response_rate                            6747 non-null   object
 16  host_acceptance_rate                          7170 non-null   object
 17  host_is_superhost                             7992 non-null   object
 18  host_thumbnail_url                            8055 non-null   object
 19  host_picture_url                              8055 non-null   object
 20  host_neighbourhood                            7718 non-null   object
 21  host_listings_count                           8055 non-null   float64
 22  host_total_listings_count                     8055 non-null   float64
 23  host_verifications                            8055 non-null   object
 24  host_has_profile_pic                          8055 non-null   object
 25  host_identity_verified                        8055 non-null   object
 26  neighbourhood                                 5613 non-null   object
 27  neighbourhood_cleansed                        8056 non-null   object
 28  latitude                                      8056 non-null   float64
 29  longitude                                     8056 non-null   float64
 30  property_type                                 8056 non-null   object
 31  room_type                                     8056 non-null   object
 32  accommodates                                  8056 non-null   int64
 33  bathrooms_text                                8047 non-null   object
 34  bedrooms                                      5 non-null      float64
 35  beds                                          7959 non-null   float64
 36  amenities                                     8056 non-null   object
 37  price                                         8056 non-null   object
 38  minimum_nights                                8056 non-null   int64
 39  maximum_nights                                8056 non-null   int64
 40  minimum_minimum_nights                        8056 non-null   int64
 41  maximum_minimum_nights                        8056 non-null   int64
 42  minimum_maximum_nights                        8056 non-null   int64
 43  maximum_maximum_nights                        8056 non-null   int64
 44  minimum_nights_avg_ntm                        8056 non-null   float64
 45  maximum_nights_avg_ntm                        8056 non-null   float64
 46  has_availability                              8056 non-null   object
 47  availability_30                               8056 non-null   int64
 48  availability_60                               8056 non-null   int64
 49  availability_90                               8056 non-null   int64
 50  availability_365                              8056 non-null   int64
 51  calendar_last_scraped                         8056 non-null   object
 52  number_of_reviews                             8056 non-null   int64
 53  number_of_reviews_ltm                         8056 non-null   int64
 54  number_of_reviews_l30d                        8056 non-null   int64
 55  first_review                                  6172 non-null   object
 56  last_review                                   6172 non-null   object
 57  review_scores_rating                          6175 non-null   float64
 58  review_scores_accuracy                        6173 non-null   float64
 59  review_scores_cleanliness                     6173 non-null   float64
 60  review_scores_checkin                         6172 non-null   float64
 61  review_scores_communication                   6173 non-null   float64
 62  review_scores_location                        6172 non-null   float64
 63  review_scores_value                           6172 non-null   float64
 64  license                                       5091 non-null   object
 65  instant_bookable                              8056 non-null   object
 66  calculated_host_listings_count                8056 non-null   int64
 67  calculated_host_listings_count_entire_homes   8056 non-null   int64
 68  calculated_host_listings_count_private_rooms  8056 non-null   int64
 69  calculated_host_listings_count_shared_rooms   8056 non-null   int64
 70  reviews_per_month                             6172 non-null   float64
dtypes: float64(16), int64(21), object(34)
memory usage: 4.4+ MB

In [6]:
# Dropping uneeded partially null columns
listings_df = listings_df.drop(['neighborhood_overview', 'host_location',
                                'host_about', 'host_response_time',
                                'host_response_rate', 'host_acceptance_rate',
                                'host_neighbourhood', 'neighbourhood', 'bedrooms', 
                                'first_review', 'last_review', 'review_scores_accuracy',
                                'review_scores_checkin', 'review_scores_communication',
                                'review_scores_location', 'reviews_per_month'], axis=1)
listings_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,picture_url,host_id,host_url,host_name,...,number_of_reviews_l30d,review_scores_rating,review_scores_cleanliness,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,138592,https://www.airbnb.com/rooms/138592,20231204023824,2023-12-04,city scrape,Home in San Francisco · ★4.91 · 4 bedrooms · 4...,https://a0.muscache.com/pictures/039b1662-ff1a...,648553,https://www.airbnb.com/users/show/648553,Julie & Brad,...,0,4.91,5.00,4.55,Pending Application,f,1,1,0,0
1,474107,https://www.airbnb.com/rooms/474107,20231204023824,2023-12-04,city scrape,Home in San Francisco · ★4.91 · 2 bedrooms · 2...,https://a0.muscache.com/pictures/181cbeb0-18b7...,2318089,https://www.airbnb.com/users/show/2318089,Inés,...,1,4.91,4.93,4.87,STR-0007772,f,1,0,1,0
2,487019,https://www.airbnb.com/rooms/487019,20231204023824,2023-12-04,city scrape,Rental unit in San Francisco · ★4.53 · 3 bedro...,https://a0.muscache.com/pictures/5789289/7a78c...,2410550,https://www.airbnb.com/users/show/2410550,Cecile,...,0,4.53,4.33,4.47,STR-0001599,f,1,1,0,0
3,487499,https://www.airbnb.com/rooms/487499,20231204023824,2023-12-04,city scrape,Rental unit in San Francisco · ★4.78 · 1 bedro...,https://a0.muscache.com/pictures/12842308/68a6...,1682183,https://www.airbnb.com/users/show/1682183,Daniel,...,1,4.78,4.84,4.60,NaN,f,1,1,0,0
4,1163946,https://www.airbnb.com/rooms/1163946,20231204023824,2023-12-04,previous scrape,Condo in San Francisco · 2 bedrooms · 2 beds ·...,https://a0.muscache.com/pictures/miso/Hosting-...,1918239,https://www.airbnb.com/users/show/1918239,Jen,...,0,4.50,4.50,4.50,NaN,f,1,1,0,0

In [7]:
# Checking for unneccarry columns to drop
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8056 entries, 0 to 8055
Data columns (total 55 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8056 non-null   int64
 1   listing_url                                   8056 non-null   object
 2   scrape_id                                     8056 non-null   int64
 3   last_scraped                                  8056 non-null   object
 4   source                                        8056 non-null   object
 5   name                                          8056 non-null   object
 6   picture_url                                   8056 non-null   object
 7   host_id                                       8056 non-null   int64
 8   host_url                                      8056 non-null   object
 9   host_name                                     8055 non-null   object
 10  host_since                                    8055 non-null   object
 11  host_is_superhost                             7992 non-null   object
 12  host_thumbnail_url                            8055 non-null   object
 13  host_picture_url                              8055 non-null   object
 14  host_listings_count                           8055 non-null   float64
 15  host_total_listings_count                     8055 non-null   float64
 16  host_verifications                            8055 non-null   object
 17  host_has_profile_pic                          8055 non-null   object
 18  host_identity_verified                        8055 non-null   object
 19  neighbourhood_cleansed                        8056 non-null   object
 20  latitude                                      8056 non-null   float64
 21  longitude                                     8056 non-null   float64
 22  property_type                                 8056 non-null   object
 23  room_type                                     8056 non-null   object
 24  accommodates                                  8056 non-null   int64
 25  bathrooms_text                                8047 non-null   object
 26  beds                                          7959 non-null   float64
 27  amenities                                     8056 non-null   object
 28  price                                         8056 non-null   object
 29  minimum_nights                                8056 non-null   int64
 30  maximum_nights                                8056 non-null   int64
 31  minimum_minimum_nights                        8056 non-null   int64
 32  maximum_minimum_nights                        8056 non-null   int64
 33  minimum_maximum_nights                        8056 non-null   int64
 34  maximum_maximum_nights                        8056 non-null   int64
 35  minimum_nights_avg_ntm                        8056 non-null   float64
 36  maximum_nights_avg_ntm                        8056 non-null   float64
 37  has_availability                              8056 non-null   object
 38  availability_30                               8056 non-null   int64
 39  availability_60                               8056 non-null   int64
 40  availability_90                               8056 non-null   int64
 41  availability_365                              8056 non-null   int64
 42  calendar_last_scraped                         8056 non-null   object
 43  number_of_reviews                             8056 non-null   int64
 44  number_of_reviews_ltm                         8056 non-null   int64
 45  number_of_reviews_l30d                        8056 non-null   int64
 46  review_scores_rating                          6175 non-null   float64
 47  review_scores_cleanliness                     6173 non-null   float64
 48  review_scores_value                           6172 non-null   float64
 49  license                                       5091 non-null   object
 50  instant_bookable                              8056 non-null   object
 51  calculated_host_listings_count                8056 non-null   int64
 52  calculated_host_listings_count_entire_homes   8056 non-null   int64
 53  calculated_host_listings_count_private_rooms  8056 non-null   int64
 54  calculated_host_listings_count_shared_rooms   8056 non-null   int64
dtypes: float64(10), int64(21), object(24)
memory usage: 3.4+ MB

In [8]:
listings_df = listings_df.drop(['listing_url', 'scrape_id', 'last_scraped',
                                'source', 'name',
                                'host_url', 'host_name',
                                'host_thumbnail_url', 'host_picture_url', 
                                'host_verifications', 'host_has_profile_pic',
                                'property_type', 'calendar_last_scraped', 
                                'number_of_reviews_l30d', 'license', 'instant_bookable'], axis=1)
listings_df.head()

,id,picture_url,host_id,host_since,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,latitude,...,availability_365,number_of_reviews,number_of_reviews_ltm,review_scores_rating,review_scores_cleanliness,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,138592,https://a0.muscache.com/pictures/039b1662-ff1a...,648553,2011-05-31,f,1.0,5.0,t,Noe Valley,37.75635,...,80,34,2,4.91,5.00,4.55,1,1,0,0
1,474107,https://a0.muscache.com/pictures/181cbeb0-18b7...,2318089,2012-05-08,t,1.0,3.0,t,Excelsior,37.72369,...,196,149,20,4.91,4.93,4.87,1,0,1,0
2,487019,https://a0.muscache.com/pictures/5789289/7a78c...,2410550,2012-05-19,f,1.0,1.0,t,Potrero Hill,37.75622,...,202,36,7,4.53,4.33,4.47,1,1,0,0
3,487499,https://a0.muscache.com/pictures/12842308/68a6...,1682183,2012-02-01,t,2.0,2.0,t,Mission,37.75884,...,149,196,4,4.78,4.84,4.60,1,1,0,0
4,1163946,https://a0.muscache.com/pictures/miso/Hosting-...,1918239,2012-03-13,f,1.0,1.0,t,Mission,37.76111,...,0,2,0,4.50,4.50,4.50,1,1,0,0

In [9]:
# Checking for unneccarry columns to drop
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8056 entries, 0 to 8055
Data columns (total 39 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8056 non-null   int64
 1   picture_url                                   8056 non-null   object
 2   host_id                                       8056 non-null   int64
 3   host_since                                    8055 non-null   object
 4   host_is_superhost                             7992 non-null   object
 5   host_listings_count                           8055 non-null   float64
 6   host_total_listings_count                     8055 non-null   float64
 7   host_identity_verified                        8055 non-null   object
 8   neighbourhood_cleansed                        8056 non-null   object
 9   latitude                                      8056 non-null   float64
 10  longitude                                     8056 non-null   float64
 11  room_type                                     8056 non-null   object
 12  accommodates                                  8056 non-null   int64
 13  bathrooms_text                                8047 non-null   object
 14  beds                                          7959 non-null   float64
 15  amenities                                     8056 non-null   object
 16  price                                         8056 non-null   object
 17  minimum_nights                                8056 non-null   int64
 18  maximum_nights                                8056 non-null   int64
 19  minimum_minimum_nights                        8056 non-null   int64
 20  maximum_minimum_nights                        8056 non-null   int64
 21  minimum_maximum_nights                        8056 non-null   int64
 22  maximum_maximum_nights                        8056 non-null   int64
 23  minimum_nights_avg_ntm                        8056 non-null   float64
 24  maximum_nights_avg_ntm                        8056 non-null   float64
 25  has_availability                              8056 non-null   object
 26  availability_30                               8056 non-null   int64
 27  availability_60                               8056 non-null   int64
 28  availability_90                               8056 non-null   int64
 29  availability_365                              8056 non-null   int64
 30  number_of_reviews                             8056 non-null   int64
 31  number_of_reviews_ltm                         8056 non-null   int64
 32  review_scores_rating                          6175 non-null   float64
 33  review_scores_cleanliness                     6173 non-null   float64
 34  review_scores_value                           6172 non-null   float64
 35  calculated_host_listings_count                8056 non-null   int64
 36  calculated_host_listings_count_entire_homes   8056 non-null   int64
 37  calculated_host_listings_count_private_rooms  8056 non-null   int64
 38  calculated_host_listings_count_shared_rooms   8056 non-null   int64
dtypes: float64(10), int64(19), object(10)
memory usage: 2.4+ MB

In [10]:
# ask team about columns 
# availability_30
# availability_60
# has_availability
# availability_90
# availability_360

In [11]:
# convert dtype of collumns to date time
listings_df['host_since'] = pd.to_datetime(listings_df['host_since'])

In [12]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8056 entries, 0 to 8055
Data columns (total 39 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8056 non-null   int64
 1   picture_url                                   8056 non-null   object
 2   host_id                                       8056 non-null   int64
 3   host_since                                    8055 non-null   datetime64[ns]
 4   host_is_superhost                             7992 non-null   object
 5   host_listings_count                           8055 non-null   float64
 6   host_total_listings_count                     8055 non-null   float64
 7   host_identity_verified                        8055 non-null   object
 8   neighbourhood_cleansed                        8056 non-null   object
 9   latitude                                      8056 non-null   float64
 10  longitude                                     8056 non-null   float64
 11  room_type                                     8056 non-null   object
 12  accommodates                                  8056 non-null   int64
 13  bathrooms_text                                8047 non-null   object
 14  beds                                          7959 non-null   float64
 15  amenities                                     8056 non-null   object
 16  price                                         8056 non-null   object
 17  minimum_nights                                8056 non-null   int64
 18  maximum_nights                                8056 non-null   int64
 19  minimum_minimum_nights                        8056 non-null   int64
 20  maximum_minimum_nights                        8056 non-null   int64
 21  minimum_maximum_nights                        8056 non-null   int64
 22  maximum_maximum_nights                        8056 non-null   int64
 23  minimum_nights_avg_ntm                        8056 non-null   float64
 24  maximum_nights_avg_ntm                        8056 non-null   float64
 25  has_availability                              8056 non-null   object
 26  availability_30                               8056 non-null   int64
 27  availability_60                               8056 non-null   int64
 28  availability_90                               8056 non-null   int64
 29  availability_365                              8056 non-null   int64
 30  number_of_reviews                             8056 non-null   int64
 31  number_of_reviews_ltm                         8056 non-null   int64
 32  review_scores_rating                          6175 non-null   float64
 33  review_scores_cleanliness                     6173 non-null   float64
 34  review_scores_value                           6172 non-null   float64
 35  calculated_host_listings_count                8056 non-null   int64
 36  calculated_host_listings_count_entire_homes   8056 non-null   int64
 37  calculated_host_listings_count_private_rooms  8056 non-null   int64
 38  calculated_host_listings_count_shared_rooms   8056 non-null   int64
dtypes: datetime64[ns](1), float64(10), int64(19), object(9)
memory usage: 2.4+ MB

In [13]:
#convert dtypes of columns to boolean 
listings_df['host_is_superhost'] = listings_df['host_is_superhost'].astype(bool)
listings_df['host_identity_verified'] = listings_df['host_identity_verified'].astype(bool)
listings_df['has_availability'] = listings_df['has_availability'].astype(bool)

In [14]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8056 entries, 0 to 8055
Data columns (total 39 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8056 non-null   int64
 1   picture_url                                   8056 non-null   object
 2   host_id                                       8056 non-null   int64
 3   host_since                                    8055 non-null   datetime64[ns]
 4   host_is_superhost                             8056 non-null   bool
 5   host_listings_count                           8055 non-null   float64
 6   host_total_listings_count                     8055 non-null   float64
 7   host_identity_verified                        8056 non-null   bool
 8   neighbourhood_cleansed                        8056 non-null   object
 9   latitude                                      8056 non-null   float64
 10  longitude                                     8056 non-null   float64
 11  room_type                                     8056 non-null   object
 12  accommodates                                  8056 non-null   int64
 13  bathrooms_text                                8047 non-null   object
 14  beds                                          7959 non-null   float64
 15  amenities                                     8056 non-null   object
 16  price                                         8056 non-null   object
 17  minimum_nights                                8056 non-null   int64
 18  maximum_nights                                8056 non-null   int64
 19  minimum_minimum_nights                        8056 non-null   int64
 20  maximum_minimum_nights                        8056 non-null   int64
 21  minimum_maximum_nights                        8056 non-null   int64
 22  maximum_maximum_nights                        8056 non-null   int64
 23  minimum_nights_avg_ntm                        8056 non-null   float64
 24  maximum_nights_avg_ntm                        8056 non-null   float64
 25  has_availability                              8056 non-null   bool
 26  availability_30                               8056 non-null   int64
 27  availability_60                               8056 non-null   int64
 28  availability_90                               8056 non-null   int64
 29  availability_365                              8056 non-null   int64
 30  number_of_reviews                             8056 non-null   int64
 31  number_of_reviews_ltm                         8056 non-null   int64
 32  review_scores_rating                          6175 non-null   float64
 33  review_scores_cleanliness                     6173 non-null   float64
 34  review_scores_value                           6172 non-null   float64
 35  calculated_host_listings_count                8056 non-null   int64
 36  calculated_host_listings_count_entire_homes   8056 non-null   int64
 37  calculated_host_listings_count_private_rooms  8056 non-null   int64
 38  calculated_host_listings_count_shared_rooms   8056 non-null   int64
dtypes: bool(3), datetime64[ns](1), float64(10), int64(19), object(6)
memory usage: 2.2+ MB

In [15]:
# .unique()
listings_df['bathrooms_text'].unique()

array(['2 baths', '1 shared bath', '1 bath', '1.5 baths',
       '4 shared baths', '1 private bath', '1.5 shared baths',
       '3 shared baths', '0 baths', '0 shared baths', '2 shared baths',
       '2.5 baths', nan, 'Half-bath', '3 baths', 'Shared half-bath',
       '3.5 baths', 'Private half-bath', '10 shared baths', '10 baths',
       '4.5 baths', '4 baths', '2.5 shared baths', '5 shared baths',
       '6 shared baths', '8 shared baths', '3.5 shared baths', '5 baths',
       '6.5 shared baths', '5.5 baths', '6 baths', '4.5 shared baths'],
      dtype=object)

In [16]:
# remove text from bathrooms_text column and store in a new column
listings_df['bathrooms'] = listings_df['bathrooms_text'].str.split().str[0]

In [17]:
listings_df['bathrooms'].unique()

array(['2', '1', '1.5', '4', '3', '0', '2.5', nan, 'Half-bath', 'Shared',
       '3.5', 'Private', '10', '4.5', '5', '6', '8', '6.5', '5.5'],
      dtype=object)

In [18]:
listings_df.loc[listings_df['bathrooms'] == 'Half-bath', 'bathrooms'] = None
listings_df.loc[listings_df['bathrooms'] == 'Shared', 'bathrooms'] = None
listings_df.loc[listings_df['bathrooms'] == 'Private', 'bathrooms'] = None

In [19]:
listings_df['bathrooms'].unique()

array(['2', '1', '1.5', '4', '3', '0', '2.5', nan, None, '3.5', '10',
       '4.5', '5', '6', '8', '6.5', '5.5'], dtype=object)

In [20]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8056 entries, 0 to 8055
Data columns (total 40 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8056 non-null   int64
 1   picture_url                                   8056 non-null   object
 2   host_id                                       8056 non-null   int64
 3   host_since                                    8055 non-null   datetime64[ns]
 4   host_is_superhost                             8056 non-null   bool
 5   host_listings_count                           8055 non-null   float64
 6   host_total_listings_count                     8055 non-null   float64
 7   host_identity_verified                        8056 non-null   bool
 8   neighbourhood_cleansed                        8056 non-null   object
 9   latitude                                      8056 non-null   float64
 10  longitude                                     8056 non-null   float64
 11  room_type                                     8056 non-null   object
 12  accommodates                                  8056 non-null   int64
 13  bathrooms_text                                8047 non-null   object
 14  beds                                          7959 non-null   float64
 15  amenities                                     8056 non-null   object
 16  price                                         8056 non-null   object
 17  minimum_nights                                8056 non-null   int64
 18  maximum_nights                                8056 non-null   int64
 19  minimum_minimum_nights                        8056 non-null   int64
 20  maximum_minimum_nights                        8056 non-null   int64
 21  minimum_maximum_nights                        8056 non-null   int64
 22  maximum_maximum_nights                        8056 non-null   int64
 23  minimum_nights_avg_ntm                        8056 non-null   float64
 24  maximum_nights_avg_ntm                        8056 non-null   float64
 25  has_availability                              8056 non-null   bool
 26  availability_30                               8056 non-null   int64
 27  availability_60                               8056 non-null   int64
 28  availability_90                               8056 non-null   int64
 29  availability_365                              8056 non-null   int64
 30  number_of_reviews                             8056 non-null   int64
 31  number_of_reviews_ltm                         8056 non-null   int64
 32  review_scores_rating                          6175 non-null   float64
 33  review_scores_cleanliness                     6173 non-null   float64
 34  review_scores_value                           6172 non-null   float64
 35  calculated_host_listings_count                8056 non-null   int64
 36  calculated_host_listings_count_entire_homes   8056 non-null   int64
 37  calculated_host_listings_count_private_rooms  8056 non-null   int64
 38  calculated_host_listings_count_shared_rooms   8056 non-null   int64
 39  bathrooms                                     8023 non-null   object
dtypes: bool(3), datetime64[ns](1), float64(10), int64(19), object(7)
memory usage: 2.3+ MB

In [21]:
# drop bathroom_text column.
listings_df = listings_df.drop(['bathrooms_text'], axis=1)

In [22]:
listings_df['price'].unique()

array(['$1,250.00', '$79.00', '$249.00', '$125.00', '$70.00', '$271.00',
       '$160.00', '$150.00', '$110.00', '$156.00', '$100.00', '$181.00',
       '$235.00', '$56.00', '$675.00', '$122.00', '$95.00', '$65.00',
       '$99.00', '$126.00', '$149.00', '$157.00', '$165.00', '$1,000.00',
       '$164.00', '$190.00', '$200.00', '$290.00', '$145.00', '$87.00',
       '$115.00', '$121.00', '$130.00', '$98.00', '$112.00', '$45.00',
       '$139.00', '$120.00', '$83.00', '$48.00', '$178.00', '$495.00',
       '$277.00', '$72.00', '$49.00', '$132.00', '$215.00', '$128.00',
       '$85.00', '$135.00', '$90.00', '$225.00', '$55.00', '$113.00',
       '$140.00', '$80.00', '$580.00', '$350.00', '$96.00', '$572.00',
       '$40.00', '$167.00', '$71.00', '$170.00', '$93.00', '$229.00',
       '$75.00', '$175.00', '$291.00', '$64.00', '$86.00', '$250.00',
       '$239.00', '$857.00', '$143.00', '$107.00', '$395.00', '$117.00',
       '$60.00', '$256.00', '$550.00', '$525.00', '$585.00', '$385.00',
       '$146.00', '$57.00', '$73.00', '$76.00', '$155.00', '$136.00',
       '$177.00', '$300.00', '$105.00', '$196.00', '$77.00', '$270.00',
       '$176.00', '$44.00', '$168.00', '$349.00', '$425.00', '$133.00',
       '$220.00', '$360.00', '$187.00', '$62.00', '$449.00', '$659.00',
       '$119.00', '$450.00', '$448.00', '$89.00', '$1,149.00', '$400.00',
       '$275.00', '$325.00', '$511.00', '$81.00', '$1,400.00', '$199.00',
       '$69.00', '$82.00', '$240.00', '$500.00', '$441.00', '$180.00',
       '$68.00', '$144.00', '$203.00', '$315.00', '$123.00', '$600.00',
       '$310.00', '$410.00', '$473.00', '$59.00', '$499.00', '$111.00',
       '$269.00', '$295.00', '$565.00', '$846.00', '$189.00', '$221.00',
       '$46.00', '$795.00', '$53.00', '$230.00', '$509.00', '$10,000.00',
       '$198.00', '$320.00', '$750.00', '$2,000.00', '$141.00', '$210.00',
       '$459.00', '$799.00', '$470.00', '$41.00', '$595.00', '$365.00',
       '$411.00', '$299.00', '$194.00', '$1,395.00', '$950.00', '$700.00',
       '$92.00', '$47.00', '$185.00', '$389.00', '$317.00', '$152.00',
       '$118.00', '$304.00', '$184.00', '$610.00', '$800.00', '$228.00',
       '$520.00', '$259.00', '$193.00', '$265.00', '$369.00', '$285.00',
       '$465.00', '$109.00', '$154.00', '$129.00', '$214.00', '$192.00',
       '$38.00', '$42.00', '$564.00', '$613.00', '$364.00', '$171.00',
       '$370.00', '$261.00', '$172.00', '$97.00', '$995.00', '$131.00',
       '$650.00', '$103.00', '$182.00', '$560.00', '$561.00', '$124.00',
       '$137.00', '$483.00', '$506.00', '$74.00', '$535.00', '$219.00',
       '$108.00', '$336.00', '$319.00', '$307.00', '$599.00', '$286.00',
       '$390.00', '$258.00', '$279.00', '$720.00', '$195.00', '$393.00',
       '$101.00', '$169.00', '$179.00', '$197.00', '$375.00', '$66.00',
       '$67.00', '$372.00', '$248.00', '$245.00', '$850.00', '$614.00',
       '$548.00', '$201.00', '$298.00', '$142.00', '$183.00', '$864.00',
       '$257.00', '$255.00', '$354.00', '$134.00', '$148.00', '$114.00',
       '$208.00', '$1,179.00', '$224.00', '$1,500.00', '$127.00',
       '$159.00', '$138.00', '$209.00', '$88.00', '$241.00', '$876.00',
       '$328.00', '$330.00', '$391.00', '$50.00', '$289.00', '$1,499.00',
       '$729.00', '$2,036.00', '$94.00', '$37.00', '$518.00', '$166.00',
       '$263.00', '$329.00', '$4,000.00', '$3,900.00', '$153.00',
       '$252.00', '$519.00', '$611.00', '$51.00', '$900.00', '$443.00',
       '$106.00', '$545.00', '$292.00', '$557.00', '$280.00', '$272.00',
       '$173.00', '$205.00', '$266.00', '$260.00', '$174.00', '$212.00',
       '$3,000.00', '$188.00', '$975.00', '$207.00', '$223.00', '$546.00',
       '$163.00', '$575.00', '$293.00', '$306.00', '$379.00', '$327.00',
       '$399.00', '$620.00', '$568.00', '$1,995.00', '$151.00', '$78.00',
       '$222.00', '$685.00', '$1,200.00', '$313.00', '$102.00', '$84.00',
       '$695.00', '$312.00', '$455.00', '$464.00', '$398.00', '$539.00',
       '$566.00', '$104.00', '$308.00', '$206.00', '$1,286.00', '$332.00',
       '$211.00', '$236.00', '$334.00', '$301.00', '$116.00', '$1,213.00',
       '$186.00', '$58.00', '$673.00', '$980.00', '$254.00', '$1,550.00',
       '$297.00', '$865.00', '$764.00', '$1,607.00', '$362.00', '$52.00',
       '$161.00', '$394.00', '$777.00', '$232.00', '$39.00', '$91.00',
       '$237.00', '$3,250.00', '$380.00', '$1,650.00', '$490.00',
       '$725.00', '$316.00', '$305.00', '$63.00', '$30.00', '$324.00',
       '$296.00', '$61.00', '$335.00', '$782.00', '$314.00', '$510.00',
       '$1,152.00', '$507.00', '$216.00', '$386.00', '$485.00', '$693.00',
       '$514.00', '$392.00', '$604.00', '$227.00', '$538.00', '$303.00',
       '$302.00', '$352.00', '$775.00', '$162.00', '$218.00', '$147.00',
       '$294.00', '$50,000.00', '$429.00', '$468.00', '$1,795.00',
       '$54.00', '$9,999.00', '$1,600.00', '$724.00', '$264.00',
       '$1,100.00', '$634.00', '$418.00', '$413.00', '$406.00', '$979.00',
       '$419.00', '$422.00', '$699.00', '$283.00', '$242.00', '$191.00',
       '$2,982.00', '$667.00', '$3,809.00', '$204.00', '$253.00',
       '$1,938.00', '$427.00', '$247.00', '$251.00', '$281.00', '$366.00',
       '$1,299.00', '$3,800.00', '$949.00', '$479.00', '$875.00',
       '$339.00', '$414.00', '$34.00', '$779.00', '$504.00', '$407.00',
       '$43.00', '$31.00', '$278.00', '$32.00', '$549.00', '$226.00',
       '$347.00', '$541.00', '$345.00', '$337.00', '$388.00', '$1,300.00',
       '$217.00', '$890.00', '$625.00', '$244.00', '$435.00', '$1,124.00',
       '$1,264.00', '$340.00', '$338.00', '$233.00', '$2,250.00',
       '$238.00', '$970.00', '$213.00', '$423.00', '$202.00', '$2,195.00',
       '$579.00', '$396.00', '$268.00', '$445.00', '$1,195.00', '$231.00',
       '$402.00', '$4,950.00', '$246.00', '$33.00', '$536.00', '$643.00',
       '$999.00', '$403.00', '$384.00', '$158.00', '$284.00', '$28.00',
       '$326.00', '$444.00', '$382.00', '$10.00', '$438.00', '$665.00',
       '$965.00', '$363.00', '$287.00', '$383.00', '$454.00', '$420.00',
       '$2,107.00', '$344.00', '$914.00', '$481.00', '$262.00', '$359.00',
       '$35.00', '$274.00', '$1,093.00', '$26.00', '$415.00', '$877.00',
       '$596.00', '$288.00', '$475.00', '$607.00', '$630.00', '$428.00',
       '$6,000.00', '$762.00', '$1,020.00', '$749.00', '$1,800.00',
       '$476.00', '$745.00', '$234.00', '$321.00', '$471.00', '$323.00',
       '$555.00', '$348.00', '$434.00', '$404.00', '$528.00', '$466.00',
       '$371.00', '$551.00', '$29.00', '$358.00', '$2,450.00', '$529.00',
       '$563.00', '$603.00', '$457.00', '$440.00', '$322.00', '$367.00',
       '$4,450.00', '$318.00', '$1,049.00', '$355.00', '$341.00',
       '$567.00', '$895.00', '$446.00', '$849.00', '$531.00', '$766.00',
       '$503.00', '$856.00', '$480.00', '$397.00', '$688.00', '$378.00',
       '$482.00', '$14,000.00', '$282.00', '$908.00', '$1,426.00',
       '$1,323.00', '$2,291.00', '$649.00', '$19,286.00', '$417.00',
       '$742.00', '$976.00', '$2,282.00', '$2,853.00', '$571.00',
       '$351.00', '$774.00', '$648.00', '$5,555.00', '$760.00', '$460.00',
       '$343.00', '$276.00', '$888.00', '$361.00', '$513.00', '$746.00',
       '$1,228.00', '$1,144.00', '$333.00', '$1,629.00', '$1,222.00',
       '$1,527.00', '$814.00', '$905.00', '$1,018.00', '$757.00',
       '$2,582.00', '$589.00', '$424.00', '$469.00', '$1,108.00',
       '$273.00', '$837.00', '$2,400.00', '$1,030.00', '$489.00',
       '$653.00', '$840.00', '$602.00', '$3,093.00', '$25,000.00',
       '$592.00', '$1,703.00', '$727.00', '$2,673.00', '$681.00',
       '$1,146.00', '$1,344.00', '$1,359.00', '$496.00', '$36.00',
       '$243.00', '$526.00', '$591.00', '$1,850.00', '$552.00', '$719.00',
       '$829.00', '$690.00', '$309.00', '$1,135.00', '$694.00',
       '$1,007.00', '$798.00', '$488.00', '$356.00', '$461.00', '$586.00',
       '$408.00', '$707.00', '$368.00', '$689.00', '$2,510.00', '$574.00',
       '$627.00', '$311.00', '$1,199.00', '$726.00', '$442.00', '$452.00',
       '$1,155.00', '$27.00', '$638.00', '$439.00', '$734.00',
       '$1,029.00', '$1,346.00', '$1,664.00', '$493.00', '$733.00',
       '$780.00', '$833.00', '$907.00', '$357.00', '$1,580.00', '$704.00',
       '$718.00', '$680.00', '$2,025.00', '$2,500.00', '$346.00',
       '$16.00', '$1,057.00', '$431.00'], dtype=object)

In [23]:
#convert text columns to float
listings_df['bathrooms'] = listings_df['bathrooms'].astype(float)
listings_df['price'] = listings_df['price'].str.replace('$','').str.replace(',', '').str.replace('.00', '').astype(int)

In [24]:
listings_df['price'].unique()

array([ 1250,    79,   249,   125,    70,   271,   160,   150,   110,
         156,   100,   181,   235,    56,   675,   122,    95,    65,
          99,   126,   149,   157,   165,  1000,   164,   190,   200,
         290,   145,    87,   115,   121,   130,    98,   112,    45,
         139,   120,    83,    48,   178,   495,   277,    72,    49,
         132,   215,   128,    85,   135,    90,   225,    55,   113,
         140,    80,   580,   350,    96,   572,    40,   167,    71,
         170,    93,   229,    75,   175,   291,    64,    86,   250,
         239,   857,   143,   107,   395,   117,    60,   256,   550,
         525,   585,   385,   146,    57,    73,    76,   155,   136,
         177,   300,   105,   196,    77,   270,   176,    44,   168,
         349,   425,   133,   220,   360,   187,    62,   449,   659,
         119,   450,   448,    89,  1149,   400,   275,   325,   511,
          81,  1400,   199,    69,    82,   240,   500,   441,   180,
          68,   144,   203,   315,   123,   600,   310,   410,   473,
          59,   499,   111,   269,   295,   565,   846,   189,   221,
          46,   795,    53,   230,   509, 10000,   198,   320,   750,
        2000,   141,   210,   459,   799,   470,    41,   595,   365,
         411,   299,   194,  1395,   950,   700,    92,    47,   185,
         389,   317,   152,   118,   304,   184,   610,   800,   228,
         520,   259,   193,   265,   369,   285,   465,   109,   154,
         129,   214,   192,    38,    42,   564,   613,   364,   171,
         370,   261,   172,    97,   995,   131,   650,   103,   182,
         560,   561,   124,   137,   483,   506,    74,   535,   219,
         108,   336,   319,   307,   599,   286,   390,   258,   279,
         720,   195,   393,   101,   169,   179,   197,   375,    66,
          67,   372,   248,   245,   850,   614,   548,   201,   298,
         142,   183,   864,   257,   255,   354,   134,   148,   114,
         208,  1179,   224,  1500,   127,   159,   138,   209,    88,
         241,   876,   328,   330,   391,    50,   289,  1499,   729,
        2036,    94,    37,   518,   166,   263,   329,  4000,  3900,
         153,   252,   519,   611,    51,   900,   443,   106,   545,
         292,   557,   280,   272,   173,   205,   266,   260,   174,
         212,  3000,   188,   975,   207,   223,   546,   163,   575,
         293,   306,   379,   327,   399,   620,   568,  1995,   151,
          78,   222,   685,  1200,   313,   102,    84,   695,   312,
         455,   464,   398,   539,   566,   104,   308,   206,  1286,
         332,   211,   236,   334,   301,   116,  1213,   186,    58,
         673,   980,   254,  1550,   297,   865,   764,  1607,   362,
          52,   161,   394,   777,   232,    39,    91,   237,  3250,
         380,  1650,   490,   725,   316,   305,    63,    30,   324,
         296,    61,   335,   782,   314,   510,  1152,   507,   216,
         386,   485,   693,   514,   392,   604,   227,   538,   303,
         302,   352,   775,   162,   218,   147,   294, 50000,   429,
         468,  1795,    54,  9999,  1600,   724,   264,  1100,   634,
         418,   413,   406,   979,   419,   422,   699,   283,   242,
         191,  2982,   667,  3809,   204,   253,  1938,   427,   247,
         251,   281,   366,  1299,  3800,   949,   479,   875,   339,
         414,    34,   779,   504,   407,    43,    31,   278,    32,
         549,   226,   347,   541,   345,   337,   388,  1300,   217,
         890,   625,   244,   435,  1124,  1264,   340,   338,   233,
        2250,   238,   970,   213,   423,   202,  2195,   579,   396,
         268,   445,  1195,   231,   402,  4950,   246,    33,   536,
         643,   999,   403,   384,   158,   284,    28,   326,   444,
         382,    10,   438,   665,   965,   363,   287,   383,   454,
         420,  2107,   344,   914,   481,   262,   359,    35,   274,
        1093,    26,   415,   877,   596,   288,   475,   607,   630,
         428,  6000,   762,  1020,   749,  1800,   476,   745,   234,
         321,   471,   323,   555,   348,   434,   404,   528,   466,
         371,   551,    29,   358,  2450,   529,   563,   603,   457,
         440,   322,   367,  4450,   318,  1049,   355,   341,   567,
         895,   446,   849,   531,   766,   503,   856,   480,   397,
         688,   378,   482, 14000,   282,   908,  1426,  1323,  2291,
         649, 19286,   417,   742,   976,  2282,  2853,   571,   351,
         774,   648,  5555,   760,   460,   343,   276,   888,   361,
         513,   746,  1228,  1144,   333,  1629,  1222,  1527,   814,
         905,  1018,   757,  2582,   589,   424,   469,  1108,   273,
         837,  2400,  1030,   489,   653,   840,   602,  3093, 25000,
         592,  1703,   727,  2673,   681,  1146,  1344,  1359,   496,
          36,   243,   526,   591,  1850,   552,   719,   829,   690,
         309,  1135,   694,  1007,   798,   488,   356,   461,   586,
         408,   707,   368,   689,  2510,   574,   627,   311,  1199,
         726,   442,   452,  1155,    27,   638,   439,   734,  1029,
        1346,  1664,   493,   733,   780,   833,   907,   357,  1580,
         704,   718,   680,  2025,  2500,   346,    16,  1057,   431])

In [25]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8056 entries, 0 to 8055
Data columns (total 39 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8056 non-null   int64
 1   picture_url                                   8056 non-null   object
 2   host_id                                       8056 non-null   int64
 3   host_since                                    8055 non-null   datetime64[ns]
 4   host_is_superhost                             8056 non-null   bool
 5   host_listings_count                           8055 non-null   float64
 6   host_total_listings_count                     8055 non-null   float64
 7   host_identity_verified                        8056 non-null   bool
 8   neighbourhood_cleansed                        8056 non-null   object
 9   latitude                                      8056 non-null   float64
 10  longitude                                     8056 non-null   float64
 11  room_type                                     8056 non-null   object
 12  accommodates                                  8056 non-null   int64
 13  beds                                          7959 non-null   float64
 14  amenities                                     8056 non-null   object
 15  price                                         8056 non-null   int64
 16  minimum_nights                                8056 non-null   int64
 17  maximum_nights                                8056 non-null   int64
 18  minimum_minimum_nights                        8056 non-null   int64
 19  maximum_minimum_nights                        8056 non-null   int64
 20  minimum_maximum_nights                        8056 non-null   int64
 21  maximum_maximum_nights                        8056 non-null   int64
 22  minimum_nights_avg_ntm                        8056 non-null   float64
 23  maximum_nights_avg_ntm                        8056 non-null   float64
 24  has_availability                              8056 non-null   bool
 25  availability_30                               8056 non-null   int64
 26  availability_60                               8056 non-null   int64
 27  availability_90                               8056 non-null   int64
 28  availability_365                              8056 non-null   int64
 29  number_of_reviews                             8056 non-null   int64
 30  number_of_reviews_ltm                         8056 non-null   int64
 31  review_scores_rating                          6175 non-null   float64
 32  review_scores_cleanliness                     6173 non-null   float64
 33  review_scores_value                           6172 non-null   float64
 34  calculated_host_listings_count                8056 non-null   int64
 35  calculated_host_listings_count_entire_homes   8056 non-null   int64
 36  calculated_host_listings_count_private_rooms  8056 non-null   int64
 37  calculated_host_listings_count_shared_rooms   8056 non-null   int64
 38  bathrooms                                     8023 non-null   float64
dtypes: bool(3), datetime64[ns](1), float64(11), int64(20), object(4)
memory usage: 2.2+ MB

In [29]:
# removing reviews columns
listings_cleaned = listings_df.drop(['review_scores_rating', 'review_scores_cleanliness', 'review_scores_value'], axis=1)
#drop null
listings_cleaned = listings_cleaned.dropna()
listings_cleaned.info()
# save master data
listings_cleaned.to_csv('Resources/listings_cleaned.csv', index=False)
listings_cleaned.to_json('Resources/listings_cleaned.json', orient='records')

<class 'pandas.core.frame.DataFrame'>
Index: 7927 entries, 0 to 8055
Data columns (total 36 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7927 non-null   int64
 1   picture_url                                   7927 non-null   object
 2   host_id                                       7927 non-null   int64
 3   host_since                                    7927 non-null   datetime64[ns]
 4   host_is_superhost                             7927 non-null   bool
 5   host_listings_count                           7927 non-null   float64
 6   host_total_listings_count                     7927 non-null   float64
 7   host_identity_verified                        7927 non-null   bool
 8   neighbourhood_cleansed                        7927 non-null   object
 9   latitude                                      7927 non-null   float64
 10  longitude                                     7927 non-null   float64
 11  room_type                                     7927 non-null   object
 12  accommodates                                  7927 non-null   int64
 13  beds                                          7927 non-null   float64
 14  amenities                                     7927 non-null   object
 15  price                                         7927 non-null   int64
 16  minimum_nights                                7927 non-null   int64
 17  maximum_nights                                7927 non-null   int64
 18  minimum_minimum_nights                        7927 non-null   int64
 19  maximum_minimum_nights                        7927 non-null   int64
 20  minimum_maximum_nights                        7927 non-null   int64
 21  maximum_maximum_nights                        7927 non-null   int64
 22  minimum_nights_avg_ntm                        7927 non-null   float64
 23  maximum_nights_avg_ntm                        7927 non-null   float64
 24  has_availability                              7927 non-null   bool
 25  availability_30                               7927 non-null   int64
 26  availability_60                               7927 non-null   int64
 27  availability_90                               7927 non-null   int64
 28  availability_365                              7927 non-null   int64
 29  number_of_reviews                             7927 non-null   int64
 30  number_of_reviews_ltm                         7927 non-null   int64
 31  calculated_host_listings_count                7927 non-null   int64
 32  calculated_host_listings_count_entire_homes   7927 non-null   int64
 33  calculated_host_listings_count_private_rooms  7927 non-null   int64
 34  calculated_host_listings_count_shared_rooms   7927 non-null   int64
 35  bathrooms                                     7927 non-null   float64
dtypes: bool(3), datetime64[ns](1), float64(8), int64(20), object(4)
memory usage: 2.1+ MB

In [31]:
# creating a review csv
#dropping null values
review_cleaned = listings_df.dropna()
review_cleaned.info()
# save review dtaframe
review_cleaned.to_csv('Resources/review_cleaned.csv', index=False)
review_cleaned.to_json('Resources/review_cleaned.json', orient='records')

<class 'pandas.core.frame.DataFrame'>
Index: 6076 entries, 0 to 7986
Data columns (total 39 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            6076 non-null   int64
 1   picture_url                                   6076 non-null   object
 2   host_id                                       6076 non-null   int64
 3   host_since                                    6076 non-null   datetime64[ns]
 4   host_is_superhost                             6076 non-null   bool
 5   host_listings_count                           6076 non-null   float64
 6   host_total_listings_count                     6076 non-null   float64
 7   host_identity_verified                        6076 non-null   bool
 8   neighbourhood_cleansed                        6076 non-null   object
 9   latitude                                      6076 non-null   float64
 10  longitude                                     6076 non-null   float64
 11  room_type                                     6076 non-null   object
 12  accommodates                                  6076 non-null   int64
 13  beds                                          6076 non-null   float64
 14  amenities                                     6076 non-null   object
 15  price                                         6076 non-null   int64
 16  minimum_nights                                6076 non-null   int64
 17  maximum_nights                                6076 non-null   int64
 18  minimum_minimum_nights                        6076 non-null   int64
 19  maximum_minimum_nights                        6076 non-null   int64
 20  minimum_maximum_nights                        6076 non-null   int64
 21  maximum_maximum_nights                        6076 non-null   int64
 22  minimum_nights_avg_ntm                        6076 non-null   float64
 23  maximum_nights_avg_ntm                        6076 non-null   float64
 24  has_availability                              6076 non-null   bool
 25  availability_30                               6076 non-null   int64
 26  availability_60                               6076 non-null   int64
 27  availability_90                               6076 non-null   int64
 28  availability_365                              6076 non-null   int64
 29  number_of_reviews                             6076 non-null   int64
 30  number_of_reviews_ltm                         6076 non-null   int64
 31  review_scores_rating                          6076 non-null   float64
 32  review_scores_cleanliness                     6076 non-null   float64
 33  review_scores_value                           6076 non-null   float64
 34  calculated_host_listings_count                6076 non-null   int64
 35  calculated_host_listings_count_entire_homes   6076 non-null   int64
 36  calculated_host_listings_count_private_rooms  6076 non-null   int64
 37  calculated_host_listings_count_shared_rooms   6076 non-null   int64
 38  bathrooms                                     6076 non-null   float64
dtypes: bool(3), datetime64[ns](1), float64(11), int64(20), object(4)
memory usage: 1.7+ MB